name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    # Checkout
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12'

    # Install Dependencies
    - name: install dependencies
      run: npm install

    # Build
    - name: build
      run: |
        npm run build:context

    # Publish
    - uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}

    # commit dist
    - name: commit docs
      uses: EndBug/add-and-commit@v2
      with: # More info about the arguments on the action page
        author_name: winetree94
        author_email: winetree94@outlook.com
        message: "commit docs"
        path: docs
        pattern: "*" # Pattern that matches the files to commit
        force: true # Whether to use the --force flag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This gets generated automatically
