# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12'

    # Runs a single command using the runners shell
    - name: install dependencies
      run: npm install

    # Runs a set of commands using the runners shell
    - name: build
      run: |
        npm run build:context

    # commit dist
    - name: commit dist
      uses: EndBug/add-and-commit@v2
      with: # More info about the arguments on the action page
        author_name: winetree94
        author_email: winetree94@outlook.com
        message: "build dist"
        path: dist
        pattern: "*" # Pattern that matches the files to commit
        force: true # Whether to use the --force flag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This gets generated automatically

  publish:
    name: Publish to NPM & GitHub Package Registry
    runs-on: ubuntu-latest
    if: contains(github.ref, 'master')
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v1.0.0
      with:
        ref: master

    - name: Check version changes
      uses: EndBug/version-check@v1.0.0
      id: check

    - name: Version update detected
      if: steps.check.outputs.changed == 'true'
      run: 'echo "Version change! -> ${{ steps.check.outputs.type }}"'

    - name: Set up Node.js for NPM
      if: steps.check.outputs.changed == 'true'
      uses: actions/setup-node@v1.2.0
      with:
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      if: steps.check.outputs.changed == 'true'
      run: npm install

    - name: Publish package to NPM
      if: steps.check.outputs.changed == 'true'
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Set up Node.js for GPR
      if: steps.check.outputs.changed == 'true'
      uses: actions/setup-node@v1.2.0
      with:
        registry-url: 'https://npm.pkg.github.com/'
        scope: '@endbug'

    - name: Set up package for GPR
      if: steps.check.outputs.changed == 'true'
      run: npm run gpr-setup

    - name: Publish package to GPR
      if: steps.check.outputs.changed == 'true'
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}